name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/dockerhub/build/vrcd-rak-profile:latest
            ${{ secrets.DOCKER_REGISTRY }}/dockerhub/build/vrcd-rak-profile:${{ github.sha }}
          build-args: |
            NODE_ENV=production

      - name: Update Deployment Image Tag in Kubernetes (Kuboard)
        run: |
          curl -X PUT \
            -k \
            -H "content-type: application/json" \
            -H "Cookie: KuboardUsername=${{ secrets.KUBOARD_USERNAME }}; KuboardAccessKey=${{ secrets.KUBOARD_ACCESS_KEY }}" \
            -d '{"kind":"deployments","namespace":"dev","name":"vrcd-rak-profile","images":{"${{ secrets.DOCKER_REGISTRY }}/dockerhub/build/vrcd-rak-profile":"${{ secrets.DOCKER_REGISTRY }}/dockerhub/build/vrcd-rak-profile:${{ github.sha }}"}}' \
            "${{ secrets.KUBOARD_API_URL }}"
