name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Docker Login to Registry
        uses: docker/login-action@v3
        with:
          registry: fox-su-docker.pkg.coding.net
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/build/vrcd-rak-profile:latest
            ${{ secrets.DOCKER_REGISTRY }}/build/vrcd-rak-profile:${{ github.sha }}
          build-args: |
            NODE_ENV=production

      - name: Deploy to Kubernetes
        run: |
          curl -X PUT \
            -H "content-type: application/json" \
            -H "Cookie: ${{ secrets.KUBERNETES_AUTH_COOKIE }}" \
            -d '{"kind":"deployments","namespace":"vrcd-uncategorized","name":"vrcd-home-d5f17b9dc114c7fb","images":{"${{ secrets.DOCKER_REGISTRY }}/build/vrcd-rak-profile":"${{ secrets.DOCKER_REGISTRY }}/build/vrcd-rak-profile:${{ github.sha }}"}}' \
            "${{ secrets.KUBERNETES_API_URL }}"